# Generated by Django 4.2.7 on 2023-12-12 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tienda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(blank=True, max_length=32, null=True)),
                ('provincia', models.CharField(blank=True, max_length=32, null=True)),
                ('region', models.CharField(blank=True, max_length=32, null=True)),
                ('fecha_creacion', models.DateField()),
                ('telefono_contacto', models.CharField(blank=True, max_length=32, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(blank=True, max_length=32, null=True)),
                ('codigo', models.CharField(blank=True, max_length=32, null=True)),
                ('precio_venta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cantidad', models.IntegerField()),
                ('tienda_relacionada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestionTienda.tienda')),
            ],
        ),
    ]
